aliases:
  - &save_cache
    name: Cache Dependencies
    key: couperose-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "couperose-haskell.cabal" }}
    paths:
      - "/root/.stack"
      - ".stack-work"
  - &restore_cache
    name: Restore Cached Dependencies
    keys:
      - couperose-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "couperose-haskell.cabal" }}
  - &store_artifacts
    path: ~/.local/bin/circleci-couperose-haskell
    destination: circleci-couperose-haskell
  - &update_dependencies
    name: Resolve/Update Dependencies
    command: stack --no-terminal setup
version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: *update_dependencies
      - run:
          name: Run tests
          command: stack --no-terminal test
      - run:
          name: Install executable
          command: stack --no-terminal install
      - save_cache: *save_cache
      - store_artifacts: *store_artifacts
