aliases:
  - &git_checkout
    name: Checkout
    command: |
      apt-get update && apt-get install -y openssh-server && \
      mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config && \
      git clone --depth 1 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
      git checkout $CIRCLE_SHA1
  - &save_cache
    name: Cache Dependencies
    key: couperose-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "couperose-haskell.cabal" }}
    paths:
      - "/root/.stack"
      - ".stack-work"
  - &restore_cache
    name: Restore Cached Dependencies
    keys:
      - couperose-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "couperose-haskell.cabal" }}
  - &store_artifacts
    path: ~/.local/bin/circleci-couperose-haskell
    destination: circleci-couperose-haskell
  - &update_dependencies
    name: Resolve/Update Dependencies
    command: stack --no-terminal setup
  - &run_tests
    name: Run tests
    command: stack --no-terminal test
  - &install_executable
    name: Install executable
    command: stack --no-terminal install
version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - run: *git_checkout
      - restore_cache: *restore_cache
      - run: *update_dependencies
      - run: *run_tests
      - run: *install_executable
      - save_cache: *save_cache
      - store_artifacts: *store_artifacts
workflows:
  version: 2.1
  build-test:
    jobs:
      - build
