aliases:
  - &git_checkout
    name: Checkout
    command: |
      apt-get update && apt-get install -y openssh-server && \
      mkdir -p ~/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config && \
      git clone --depth=1 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
      git checkout $CIRCLE_SHA1
  - &work_dir ~/project
  - &attach_workspace
    at: ~/project
  - &persist_to_workspace
    root: .
    paths:
      - .
  - &save_cache
    name: Cache Dependencies
    key: couperose-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "couperose-haskell.cabal" }}
    paths:
      - "/root/.stack"
      - ".stack-work"
  - &restore_cache
    name: Restore Cached Dependencies
    keys:
      - couperose-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "couperose-haskell.cabal" }}
  - &store_artifacts
    path: ~/.local/bin/couperose-haskell
    destination: circleci-couperose-haskell
  - &update_dependencies
    name: Resolve/Update Dependencies
    command: stack --no-terminal setup
  - &run_tests
    name: Run tests
    command: stack --no-terminal test
  - &install_executable
    name: Install executable
    command: stack --no-terminal install

# -------------------------
#        JOBS
# -------------------------
version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    working_directory: *work_dir
    steps:
      - run: *git_checkout
      - restore_cache: *restore_cache
      - run: *update_dependencies
      - save_cache: *save_cache
      - persist_to_workspace: *persist_to_workspace
  test: 
    docker:
      - image: fpco/stack-build:lts
    working_directory: *work_dir
    steps:
      - attach_workspace: *attach_workspace
      - run: *run_tests
  install_and_store_artifacts:
    docker:
      - image: fpco/stack-build:lts
    working_directory: *work_dir
    steps:
      - attach_workspace: *attach_workspace
      - run: *install_executable
      - store_artifacts: *store_artifacts
# -------------------------
#        WORK FLOWS
# -------------------------
workflows:
  version: 2.1
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - install_and_store_artifacts:
          requires:
            - test
